spring:
  datasource:
    url: jdbc:mysql://db1:3306/gz-day014?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: offcn123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.offcn.po